# NumPy Practice

## To begin:
We start by importing numpy and giving it an alias for easier access. We then create an array of 15 number (0-14) and place the numbers in a 3x5 structure

In [6]:
import numpy as np

a = np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


If we left the `.reshape(3,5)` off, we would get a simple python list

In [7]:
b = np.arange(15)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


 The `.shape` function allows us to find out what dimensions our NumPy array is in.

In [8]:
a.shape

(3, 5)